board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('write/', views.write_article, name='write_article'),
    path('add/', views.add, name='add_article'),
    path('<int:article_id>/', views.view, name='view_article'),
    path('update/<int:article_id>/', views.update, name='update_article'),
    path('delete/<int:article_id>/', views.delete, name='delete_article'),
]

sku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
]

board/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    write_date = models.DateTimeField(default=now, editable=False)
    write_id = models.CharField(max_length=50)

    def __str__(self):
        return self.title
    

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notice
from django.urls import reverse
from django.utils import timezone

# Create your views here.
def index(request):
    article_list = Notice.objects.all().order_by('-write_date')
    context = {'article_list': article_list}
    return render(request, 'board/index.html', context)


def write_article(request):
    return render(request, 'board/write.html')

def add(request):
    notice = Notice()
    notice.title = request.POST['i_title']
    notice.content = request.POST['i_content']
    notice.write_id = 'TestUser01'
    notice.save()

    return redirect(reverse('board:index'))

def view(request, article_id):
    notice = get_object_or_404(Notice, pk=article_id)
    return render(request, 'board/view.html', {'article':notice})

def update(request, article_id):
    notice = Notice.objects.get(id=article_id)

    if request.method == 'POST' :
        notice.title = request.POST['title']
        notice.content = request.POST['content']
        notice.write_date = timezone.datetime.now()
        notice.save()
        return redirect(reverse('board:view_article', args=(article_id,)))
    else :
        return render(request, 'board/index.html', {'article': notice})
    

def delete(request, article_id):
    notice = Notice.objects.get(id=article_id)
    notice.delete()

    return redirect(reverse('board:index'))

templates/board/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>글 목록</title>

    <style>
        .cls2 {

            text-align: center;
            font-size: 30px;
            display: block;

        }

        .cls1 {
            text-decoration: none;
        }
    </style>

</head>

<body>
    <table align="center" border="1" width="80%">
        <thead>
            <tr height="30" aligh="center" bgcolor="lightgreen">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>

        {% if not article_list %}
        <tbody>
            <tr height="30">
                <td colspan="4">
                    <p aligh="center">
                        <b><span style="font-size: 12pt">등록된 글이 없습니다.</span></b>
                    </p>
                </td>
            </tr>
        </tbody>

        {% else %}
        <tbody>
            {% for article in article_list %}
            <tr height="30" align="center">
                <td width="5%">{{forloop.counter}}</td>
                <td width="10%">{{article.write_id}}</td>
                <td align="left" width="35%">
                    <a class="cls1" href="{% url 'board:view_article' article.id %}">
                        <span style="padding-right: 30px;">{{ article.title }}</span>
                    </a>
                </td>
                <td width="5%">{{article.write_date}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}

    </table>
    <div align="center" style="margin-top: 10px;">
        <a href="{% url 'board:write_article' %}" class="cls1"><span class="cls2">글 쓰기</span></a>
    </div>

</body>

</html>

templates/board/view.html
<html>

<head>
    <title>상세 조회</title>

    <style>
        #tr_btn_modify {
            display: none;
        }
    </style>

    <script>
        function backToList(frm) {
            frm.action = "{% url 'board:index' %}";
            frm.submit();
        }

        function fn_enable() {
            document.querySelector('#i_title').disabled = false;
            document.querySelector('#i_content').disabled = false;
            document.querySelector('#tr_btn').style.display = 'none';
            document.querySelector('#tr_btn_modify').style.display = 'table-row';
        }

        function fn_modify_article(frm) {
            frm.action = "{% url 'board:update_article' article.id %}";
            frm.submit();
        }

        function fn_delete_article(frm) {
            frm.action = "{% url 'board:delete_article' article.id %}";
            frm.submit();
        }

        function fn_modify_cancel_v1() {

            document.querySelector('#i_title').disabled = true;
            document.querySelector('#i_content').disabled = true;
            document.querySelector('#tr_btn').style.display = 'table-row';
            document.querySelector('#tr_btn_modify').style.display = 'none';

        }

        function fn_modify_cancel_v2(frm) {

            frm.action = "{% url 'board:view_article' article.id %}";
            frm.submit();

        }


    </script>

</head>

<body>
    <form name="articleForm" method="POST">
        {% csrf_token %}
        <table border="0" align="center">
            <tbody>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">글 번호</td>
                    <td>
                        <input type="text" value="{{article.id}}" disabled>
                        <input type="hidden" value="{{article.article_no}}" name="articleNo">
                    </td>
                </tr>

                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">작성자</td>
                    <td>
                        <input type="text" value="{{article.write_id}}" name="writer" disabled>
                    </td>
                </tr>

                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">제목</td>
                    <td>
                        <input type="text" value="{{article.title}}" name="title" id="i_title" disabled>
                    </td>
                </tr>

                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">내용</td>
                    <td>
                        <textarea rows="20" cols="60" name="content" id="i_content"
                            disabled>{{article.content}}</textarea>
                    </td>
                </tr>

                <tr>
                    <td width="20%" align="center" bgcolor="#FF9933">작성일</td>
                    <td>
                        <input type="text" value="{{article.write_date}}" disabled>
                    </td>
                </tr>

                <tr id="tr_btn">
                    <td colspan="2" align="center">
                        <input type="button" value="수정하기" onclick="fn_enable()">
                        <input type="button" value="삭제하기" onclick="fn_delete_article(articleForm)">
                        <input type="button" value="목록보기" onclick="backToList(articleForm)">
                    </td>
                </tr>

                <tr id="tr_btn_modify">
                    <td colspan="2" align="center">
                        <input type="button" value="저장" onclick="fn_modify_article(articleForm)">
                        <input type="button" value="취소_V1" onclick="fn_modify_cancel_v1()">
                        <input type="button" value="취소_V2" onclick="fn_modify_cancel_v2(articleForm)">
                    </td>
                </tr>

            </tbody>
        </table>
    </form>
</body>

</html>

templates/board/write.html
<html>

<head>
    <title>글쓰기 페이지</title>

    <style>
        .class-caption {
            width: 100px;
        }

        .class-content {
            width: 500px;
        }
    </style>

    <script>

        function backToList(frm) {

            frm.action = "{% url 'board:index' %}";
            frm.submit();
        }

    </script>

</head>

<body>
    <h1 style="text-align: center;">글쓰기</h1>
    <form name="articleForm" method="POST" action="{% url 'board:add_article' %}">
        {% csrf_token %}
        <table border="0" align="center">
            <tbody>
                <tr>
                    <td align="right" class="class-caption">글 제목</td>
                    <td colspan="2">
                        <input type="text" maxlength="100" name="i_title" class="class-content"
                            placeholder="글의 제목을 입력해주세요!">
                    </td>
                </tr>

                <tr>
                    <td align="right" valign="top" class="class-caption"><br>글 내용 :</td>
                    <td colspan="2">
                        <textarea rows="10" maxlength="2000" name="i_content" class="class-content"
                            placeholder="글의 내용을 입력해주세요!"></textarea>
                    </td>
                </tr>

                <tr>
                    <td align="right"></td>
                    <td colspan="2">
                        <input type="submit" value="저장" onclick="fn_modify_article(articleForm)">
                        <input type="button" value="글 목록" onclick="backToList(articleForm)">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</body>

</html>